<nav>
	<?php 
		$start_num = ($page->current > 5) ? ($page->current - 5) : 1;
		$total_num = (($start_num + 9) <= $page->total_pages) ? (($start_num + 9) ) : $page->total_pages;
		$params = $_GET;
		$params['page'] = $page->before;
		unset($params['_url']);
	?>
	<ul class="pagination">
		<li>共 <?= $page->total_pages ?> 页 共 <?= $page->total_items ?> 条</a></li>
		<li><a href="<?= $this->url->get($url, $params) ?>"> <span aria-hidden="true">&laquo;</span> </a></li>
		<?php
		for ($i = $start_num; $i <= $total_num; $i++) {
		$params['page'] = $i;
		$fullurl = $this->url->get($url, $params);
		if ($i == $page->current) {
		?>
		<li class="active"><span><?= $i ?></span></li>
		<?php
		} else {
		?>
		<li><a href="<?= $fullurl ?>"><?= $i ?></a></li>
		<?php
		}}
		
		$params['page'] = $page->next;
		?>
		<li><a href="<?= $this->url->get($url, $params) ?>"> <span aria-hidden="true">&raquo;</span> </a></li>
	</ul>
</nav>
