<div class="panel panel-default">
	<div class="panel-heading"><?= $title ?></div>
	<div class="panel-body">
		<p><?php $this->flashSession->output() ?></p>
		<form method="post">
			<?php foreach($labels as $key => $label) { ?>
			<div class="form-group <?= \Phalcon\Arr::choice($errors, $key, 'has-error')?>">
				<label><?= \Phalcon\Arr::get($errors, $key, $label) ?></label>
				<?php
				/*
				    if ($key == '渠道接口人') {
						echo $this->tag->select(
							array(
								"渠道接口人",
								\Users::find(array(
									array( 'group' => '商务人员')
								)),
								"using" => array("id", "fullname")
							)
						);
				} 
				*/
				?>
					<input name="<?= $key ?>" type="text" class="form-control" placeholder="<?= $label ?>" value="<?= \Phalcon\Arr::get($data, $key) ?>">

			</div>
			<?php } ?>
			<button type="submit" class="btn btn-default">保存</button>
		</form>
	</div>
</div>