<div class="panel panel-default">
	<div class="panel-heading">游戏推广数据</div>
	<div class="panel-body">
		<form class="form-inline" method="get" action="#">
			<div class="form-group">
				<label>应用名称</label>
				<?php
				echo $this->tag->textField(array(
					'应用名称',
					'value' => $this->getQuery('应用名称'),
					'class' => 'form-control'
						)
				);
				?>
			</div>
			<div class="form-group">
				<label>游戏名称</label>
				<?php
				echo $this->tag->textField(array(
					'游戏名称',
					'value' => $this->getQuery('游戏名称'),
					'class' => 'form-control'
						)
				);
				?>
			</div>
			<div class="form-group">
				<label>日期</label>
                                <?php
                                echo $this->tag->dateField(array(
                                        'sd',
                                        'value' => $this->getQuery('sd'),
                                        'class' => 'form-control'
                                                )
                                );
                                ?>
                                -
                                <?php
                                echo $this->tag->dateField(array(
                                        'ed',
                                        'value' => $this->getQuery('ed'),
                                        'class' => 'form-control'
                                                )
                                );
                                ?>
			</div>
			<div class="input-group">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</span>
			</div>
		</form>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<?php foreach ($labels as $label) { ?>
					<th><?= $label ?></th>
				<?php } ?>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($page->items as $item) { ?>
				<tr>
					<th></th>
					<?php foreach ($labels as $key => $label) { ?>
						<td><?php
							if ($item[$key] instanceof MongoDate) {
				                                echo date('Y-m-d', $item[$key]->sec);
                        				} else {
							 echo $item[$key];
							}
							?>
						</td>
					<?php } ?>
					<td>
					</td>
				</tr>
			<?php } ?>
		</tbody>
		<tfoot>
			<tr>
				<th>总计</th>
				<?php foreach ($labels as $key => $label) { ?>
					<td>
					<?php
						echo \Phalcon\Arr::get($totals, $key);
					?>
					</td>
				<?php } ?>
			</tr>
		</tfoot>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'manage/cps/group/', 'param' => NULL)) ?>
</div>
