<div class="panel panel-default">
	<div class="panel-heading">推广数据</div>
	<div class="panel-body">
		<form class="form-inline" method="get" action="#">
			<div class="form-group">
				<label>渠道号</label>
				<?php
				echo $this->tag->textField(array(
					'渠道号', 
					'value' => $this->getQuery('渠道号'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="form-group">
				<label>厂商</label>
				<?php
				echo $this->tag->textField(array(
					'厂商名称', 
					'value' => $this->getQuery('厂商名称'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="form-group">
				<label>日期</label>
				<?php
				echo $this->tag->textField(array(
					'日期', 
					'value' => $this->getQuery('日期'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="input-group">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</span>
			</div>
		</form>
	</div>
	<table class="table">
		<thead>
			<tr>
				<?php foreach ($labels as $label) { ?>
					<th><?= $label ?></th>
				<?php } ?>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($page->items as $item) { ?>
				<tr>
					<?php foreach ($labels as $key => $label) { ?>
						<td><?= $item[$key] ?></td>
					<?php } ?>
					<td>
					</td>
				</tr>
			<?php } ?>
		</tbody>
		<tfoot>
			<tr>
				<?php foreach ($labels as $key => $label) { ?>
					<td>
					<?php
					if (strpos($label, '收益') !== false) {
						echo \Phalcon\Arr::sum($page->items, '*.'.$key, 0);
					}
					?>
					</td>
				<?php } ?>
			</tr>
			<tr>
				<?php foreach ($labels as $key => $label) { ?>
					<td>
					<?php
						echo \Phalcon\Arr::get($totals, $key);
					?>
					</td>
				<?php } ?>
			</tr>
		</tfoot>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'manage/cps/group/', 'param' => NULL)) ?>
</div>
