<div class="panel panel-default">
	<div class="panel-heading">游戏推广数据</div>
	<div class="panel-body">
		<form class="form-inline" method="get" action="#">
			<div class="form-group">
				<label>渠道号</label>
				<?php
				echo $this->tag->textField(array(
					'渠道号', 
					'value' => $this->getQuery('渠道号'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="form-group">
				<label>厂商</label>
				<?php
				echo $this->tag->textField(array(
					'厂商名称', 
					'value' => $this->getQuery('厂商名称'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="form-group">
				<label>日期</label>
				<?php
				echo $this->tag->textField(array(
					'日期', 
					'value' => $this->getQuery('日期'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="form-group">
				<?php
				echo $this->tag->selectStatic(
				    array(
					't',
					$labels,
					'value' => $this->getQuery('t'),
					'class' => 'form-control'
				    )
				);
				?>
			</div>
			<div class="input-group">
				<input type="text" placeholder="搜索..." class="form-control" name="q" value="<?= $this->getQuery('q') ?>">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</span>
			</div>
		</form>
	</div>
	<table class="table">
		<thead>
			<tr>
				<?php foreach ($labels as $label) { ?>
					<th><?= $label ?></th>
				<?php } ?>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($page->items as $item) { ?>
				<tr>
					<?php foreach ($labels as $key => $label) { ?>
						<td><?= $item->{$key} ?></td>
					<?php } ?>
					<td>
					<?php if ($this->session->get('group') == '超级管理员') { ?>
					<a class="btn btn-default" href="<?= $this->url->get('manage/cps/edit/'.$item->getIdString()) ?>">编辑</a>
					<a class="btn btn-default" href="<?= $this->url->get('manage/cps/del/'.$item->getIdString()) ?>">删除</a>
					<?php } ?>
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'manage/cps/index/', 'param' => NULL)) ?>
</div>