<div class="panel panel-default">
	<div class="panel-heading">游戏推广数据</div>
	<div class="panel-body">
		<form class="form-inline" method="get" action="#">
			<div class="form-group">
				<label>应用名称</label>
				<?php
				echo $this->tag->textField(array(
					'应用名称',
					'value' => $this->getQuery('应用名称'),
					'class' => 'form-control'
						)
				);
				?>
			</div>
			<div class="form-group">
				<label>游戏名称</label>
				<?php
				echo $this->tag->textField(array(
					'游戏名称',
					'value' => $this->getQuery('游戏名称'),
					'class' => 'form-control'
						)
				);
				?>
			</div>
			<div class="form-group">
				<label>日期</label>
				<?php
				echo $this->tag->dateField(array(
					'sd',
					'value' => $this->getQuery('sd'),
					'class' => 'form-control'
						)
				);
				?>
				-
				<?php
                                echo $this->tag->dateField(array(
                                        'ed',
                                        'value' => $this->getQuery('ed'),
                                        'class' => 'form-control'
                                                )
                                );
                                ?>
			</div>
			<div class="form-group">
				<?php
				echo $this->tag->selectStatic(
						array(
							't',
							$labels,
							'value' => $this->getQuery('t'),
							'class' => 'form-control'
						)
				);
				?>
			</div>
			<div class="input-group">
				<input type="text" placeholder="搜索..." class="form-control" name="q" value="<?= $this->getQuery('q') ?>">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</span>
			</div>
		</form>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<?php foreach ($labels as $label) { ?>
					<th><?= $label ?></th>
				<?php } ?>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			$items = array();
			foreach ($page->items as $item) {
			$items[] = $item->toArray();
			?>
				<tr>
					<th></th>
					<?php foreach ($labels as $key => $label) { ?>
						<td><?= $item->{$key} ?></td>
					<?php } ?>
					<td>
						<?php if ($this->session->get('group') == '超级管理员') { ?>
							<a class="btn btn-default" href="<?= $this->url->get('manage/cps/edit/' . $item->getIdString()) ?>">编辑</a>
							<a class="btn btn-default" href="<?= $this->url->get('manage/cps/del/' . $item->getIdString()) ?>">删除</a>
						<?php } ?>
					</td>
				</tr>
			<?php } ?>
		</tbody>
		<tfoot>
			<tr>
				<th>总计</th>
				<?php foreach ($labels as $key => $label) { ?>
					<td>
					<?php
						echo \Phalcon\Arr::get($totals, $key);
					?>
					</td>
				<?php } ?>
			</tr>
		</tfoot>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'manage/cps/index/', 'param' => NULL)) ?>
</div>
