<div class="panel panel-default">
        <div class="panel-heading">计费信息</div>
	<table class="table">
                <thead>
                        <tr>
                                <?php foreach ($labels as $label) { ?>
                                        <th><?= $label ?></th>
                                <?php } ?>
                        </tr>
                </thead>
                <tbody>
                        <?php
                        foreach ($page->items as $item) {
                        ?>
                                <tr>
				<?php foreach ($labels as $key => $label) { ?>
					<td><?= $item->{$key} ?></td>
				<?php } ?>
                                </tr>
                        <?php } ?>
                </tbody>
	</table>
</div>

