<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport" />
		<title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
		<link href="<?= $this->url->getStatic('media/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
		<link href="<?= $this->url->getStatic('media/css/style.css') ?>" rel="stylesheet" type="text/css"/>
		<script src="<?= $this->url->getStatic('media/js/jquery-1.11.1.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/bootstrap.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/notify.min.js') ?>" type="text/javascript"></script>
	</head>
	<body>
		<div class="header">
			<nav class="navbar navbar-inverse" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<a class="navbar-brand text-logo" href="<?= $this->url->getBaseUri() ?>">CPS</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<li class="active"><a href="<?= $this->url->getBaseUri() ?>">首页</a></li>
						<li><a href="<?= $this->url->get('manage/index/index') ?>"><?= $this->getSession('username', '账户')?></a></li>
						<li><a href="#service">服务</a></li>
						<li><a href="#faq">帮助</a></li>
					</ul>
				</div>
			</nav>
			<?php $this->flashSession->output('notify') ?>
			<?= $this->getContent() ?>
		</div>

		<section class="footer footer-top">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<h3>XXXX 科技有限公司</h3>
						<p>我们拥有年轻而富有创造力的团队。</p>
						<p>我们帮助您轻松管理商业数据以及客户。</p>
					</div>
					<div class="col-md-3">
						<div class="contact-info">
							<h3>联系我们</h3>
							<ul class="contact-list">
								<li><i class="glyphicon glyphicon-record"></i> 江西省抚州市</li>
								<li><i class="glyphicon glyphicon-earphone"></i> + 13699999999</li>
								<li><i class="glyphicon glyphicon-envelope"></i><a href="mailto:contact@qq.com">contact@qq.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-2">				
						<h3>快捷链接</h3>
						<ul class="quick-links">
							<li><a href="#">公司简介</a></li>
							<li><a href="#">免责声明</a></li>
							<li><a href="#">服务条款</a></li>
							<li><a href="#">条款 &amp; 招聘</a></li>
							<li><a href="#">隐私政策</a></li>
						</ul>
					</div>
					<div class="col-sm-3">
						<h3>关注我们</h3>
						<p>我们的网络社区</p>
						<ul class="social">
							<li class="red"><a href="#"> <i class="glyphicon glyphicon-heart"></i> </a> </li>
							<li><a href="#"> <i class="glyphicon glyphicon-eye-open"></i> </a> </li>
							<li><a href="#"> <i class="glyphicon glyphicon-leaf"></i> </a> </li>
							<li><a href="#"> <i class="glyphicon glyphicon-asterisk"></i> </a> </li>
						</ul>
					</div>
				</div>
			</div>
		</section>
		<footer class="footer footer-sub">
			<div class="container">
				<div class="row">
					<p>&copy; 2014 © 2014 抚州无线互联 赣ICP证000000号</p>
				</div>
			</div>
		</footer>
	</div>
</body>
</html>