<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport" />
		<title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
		<link href="<?= $this->url->getStatic('media/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
		<link href="<?= $this->url->getStatic('media/css/style.css') ?>" rel="stylesheet" type="text/css"/>
		<script src="<?= $this->url->getStatic('media/js/jquery-1.11.1.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/bootstrap.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/notify.min.js') ?>" type="text/javascript"></script>
	</head>
	<body>
		<div class="header">
			<nav class="navbar navbar-inverse" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<a class="navbar-brand text-logo" href="<?= $this->url->getBaseUri() ?>">推广</a>
					</div>
				</div>
			</nav>
			<?php $this->flashSession->output('notify') ?>
			<?= $this->getContent() ?>
		</div>
	</div>
</body>
</html>
