<div class="banner-content">
	<div class="container">
		<div class="row">
			<div class="banner-form">
				<div class="form-title">
					<h2>一个帐户，畅享 优途 所有服务！</h2>
				</div>
				<div class="form-body">
					<p>创建您的帐户</p>
					<p><?php $this->flashSession->output() ?></p>
					<form class="form" method="post" action="<?= $this->url->get('auth/reg') ?>">
						<div class="form-group<?= \Phalcon\Arr::choice($errors, 'username', ' has-error') ?>">
							<label class="control-label" for="email"><?= \Phalcon\Arr::get($errors, 'username', '账户') ?></label>
							<input name="username" type="text" class="form-control" required placeholder="您的账户" value="<?= $this->getPost('email') ?>">
						</div>
						<div class="form-group<?= \Phalcon\Arr::choice($errors, 'password', ' has-error') ?>">
							<label class="control-label" for="password"><?= \Phalcon\Arr::get($errors, 'password', '密码') ?></label>
							<input name="password" type="password" class="form-control" required placeholder="您的密码" value="<?= $this->getPost('password') ?>">
						</div>
						<div class="form-group">
							<div class="row">
								<div class="col-sm-6">
									<button type="submit" class="btn btn-default btn-submit">立即注册</button>
								</div>
								<div class="col-sm-6">
									<a class="btn btn-link" href="<?= $this->url->get('auth/index') ?>">使用已有账户登录</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>