<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport" />
		<title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
		<link href="<?= $this->url->getStatic('media/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
		<link href="<?= $this->url->getStatic('media/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css"/>
		<link href="<?= $this->url->getStatic('media/css/account.css') ?>" rel="stylesheet" type="text/css"/>
		<script src="<?= $this->url->getStatic('media/js/jquery-1.11.1.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/bootstrap.min.js') ?>" type="text/javascript"></script>
		<script src="<?= $this->url->getStatic('media/js/notify.min.js') ?>" type="text/javascript"></script>
	</head>
	<body>
		<header class="navbar navbar-inverse navbar-static-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand text-logo" href="<?= $this->url->getBaseUri() ?>">推广</a>
				</div>
				<div class="navbar-right">
					<ul class="nav navbar-nav">
						<li><a href="#"><i class="glyphicon glyphicon-envelope"></i><span class="label label-success">4</span></a></li>
						<li><a href="<?= $this->url->get('member/account/index') ?>"><?= $this->getSession('fullname', '账户') ?></a></li>
						<li><a href="<?= $this->url->getBaseUri() ?>">返回首页</a></li>
						<li><a href="<?= $this->url->get('auth/logout') ?>">退出</a></li>
					</ul>
				</div>
			</div>
		</header>
		<?php $this->flashSession->output('notify') ?>
		<div class="container-fluid">
			<aside class="col-lg-2 col-md-3">
				<section class="sidebar">
					<div class="panel panel-default">
						<div class="panel-heading">
							菜单
						</div>
						<div class="panel-body">
							<ul class="list-group">
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/bill/index') ?>"><span>计费信息</span></a>
								</li>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/cps/index') ?>">
										<span>推广数据明细</span>
									</a>
								</li>
								<?php if ($this->session->get('group') == '超级管理员') { ?>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/cps/group') ?>">
										<span>推广数据分组统计</span>
									</a>
								</li>
								<?php } ?>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/account/password') ?>">
										<span>修改密码</span>
									</a>
								</li>
							</ul>
						</div>
						<?php if ($this->session->get('group') == '超级管理员') { ?>
						<ul class="list-group">
							<li class="list-group-item">
								</i> <span>管理</span>
							</li>
						</ul>
						<div class="panel-body">
							<ul class="list-group">
								<li class="list-group-item">
                                                                        <a href="<?= $this->url->get('manage/ad/index') ?>">
                                                                                <span>广告查询</span>
                                                                        </a>
                                                                </li>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/user/index') ?>">
										<span>用户 管理</span>
									</a>
								</li>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/cps/add') ?>">
										<span>推广数据录入</span>
									</a>
								</li>
								<li class="list-group-item">
									<a href="<?= $this->url->get('manage/cps/import') ?>">
										<span>推广数据导入</span>
									</a>
								</li>
								<li class="list-group-item">
                                                                        <a href="<?= $this->url->get('manage/cps/drop') ?>">
                                                                                <span>推广数据清空</span>
                                                                        </a>
                                                                </li>
							</ul>
						</div>
						<?php } ?>
					</div>
				</section>
			</aside>
			<aside class="col-lg-10 col-md-9">
				<?= $this->getContent() ?>
			</aside>
		</div>
	</div>
</body>
</html>
