<div class="panel panel-default">
	<div class="panel-heading">修改密码</div>
	<div class="panel-body">
		<p><?php $this->flashSession->output() ?></p>
		<form method="POST" role="form">
			<div class="form-group">
				<label for="old-password">原始密码</label>
				<input name="old-password" type="password" class="form-control" placeholder="请输入您的原始密码">
			</div>
			<div class="form-group">
				<label for="password">新密码</label>
				<input name="password" type="password" class="form-control" placeholder="您的新密码">
			</div>
			<button type="submit" class="btn btn-default">保存</button>
		</form>
	</div>
</div>