<div class="panel panel-default">
        <div class="panel-heading">计费信息</div>
	<div class="panel-body">
		<p><?php $this->flashSession->output() ?></p>
		<form class="form-inline">
		<input name="operator" type="text" class="form-control input-sm" placeholder="运营商" value="<?= $this->getQuery('operator') ?>">
		<input name="countryISO" type="text" class="form-control input-sm" placeholder="国家" value="<?= $this->getQuery('countryISO') ?>">
		<input name="moContent" type="text" class="form-control input-sm" placeholder="内容" value="<?= $this->getQuery('moContent') ?>">
		<input name="addtime" type="text" class="form-control input-sm" placeholder="发出时间" value="<?= $this->getQuery('addtime') ?>">
                <button type="submit" name="search" class="btn btn-sm">搜索</button>
		</form>
	</div>
	<table class="table">
                <thead>
                        <tr>
                                <?php foreach ($labels as $label) { ?>
                                        <th><?= $label ?></th>
                                <?php } ?>
                        </tr>
                </thead>
                <tbody>
                        <?php
                        foreach ($page->items as $item) {
                        ?>
                                <tr>
				<?php foreach ($labels as $key => $label) { ?>
					<td><?= $item->{$key} ?></td>
				<?php } ?>
                                </tr>
                        <?php } ?>
                </tbody>
		<tr>
			<?php foreach ($labels as $key => $label) { ?>
				<td>
				<?php
					echo \Phalcon\Arr::get($totals, $key);
				?>
				</td>
			<?php } ?>
		</tr>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'manage/bill2/index')) ?>
</div>

